import { ImageData } from "../../imageGallery/ImageStorageRepo";
import { UserLightModel } from "../../user/UserModel";
import { CsMap } from "../nadeSubTypes/CsgoMap";
import { GameMode } from "../nadeSubTypes/GameMode";
import { Movement } from "../nadeSubTypes/Movements";
import { NadeType } from "../nadeSubTypes/NadeType";
import { TeamSide } from "../nadeSubTypes/TeamSide";
import { Technique } from "../nadeSubTypes/Technique";
import { Tickrate } from "../nadeSubTypes/Tickrate";

export type NadeCreateModel = {
  commentCount: number;
  description: string;
  endPosition: string;
  favoriteCount: number;
  youTubeId: string;
  imageLineup: ImageData;
  imageLineupThumb: ImageData;
  imageMain: ImageData;
  imageMainThumb: ImageData;
  map: CsMap;
  mapStartLocationId: string;
  mapEndLocationId: string;
  movement: Movement;
  oneWay?: boolean;
  proUrl?: string;
  setPos?: string;
  startPosition: string;
  steamId: string;
  teamSide: TeamSide;
  technique: Technique;
  tickrate?: Tickrate;
  type: NadeType;
  user: UserLightModel;
  viewCount: number;
  gameMode: GameMode;
};
