import { ImageData } from "../../imageGallery/ImageStorageRepo";
import { UserLightModel } from "../../user/UserModel";
import { CsgoMap } from "../nadeSubTypes/CsgoMap";
import { Movement } from "../nadeSubTypes/Movements";
import { NadeType } from "../nadeSubTypes/NadeType";
import { TeamSide } from "../nadeSubTypes/TeamSide";
import { Technique } from "../nadeSubTypes/Technique";
import { Tickrate } from "../nadeSubTypes/Tickrate";
import { GfycatData } from "./GfycatData";
import { MapCoordinates } from "./MapCoordinates";

export type NadeCreateModel = {
  commentCount: number;
  description: string;
  endPosition: string;
  favoriteCount: number;
  gfycat: GfycatData;
  youTubeId?: string;
  imageLineup: ImageData;
  imageLineupThumb: ImageData;
  imageMain: ImageData;
  map: CsgoMap;
  mapEndCoord: MapCoordinates;
  movement: Movement;
  oneWay?: boolean;
  proUrl?: string;
  setPos?: string;
  startPosition: string;
  steamId: string;
  teamSide: TeamSide;
  technique: Technique;
  tickrate?: Tickrate;
  type: NadeType;
  user: UserLightModel;
  viewCount: number;
};
